# Generated by Django 6.0.2 on 2026-03-11 06:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('bus_type', models.CharField(choices=[('standard', 'Standard Bus'), ('express', 'Express Bus'), ('luxury', 'Luxury Bus')], default='standard', max_length=20)),
                ('license_plate', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['bus_number'],
            },
        ),
        migrations.CreateModel(
            name='BusJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('available_seats', models.IntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('current_lat', models.FloatField(default=0.0)),
                ('current_lng', models.FloatField(default=0.0)),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='booking.bus')),
            ],
            options={
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_email', models.EmailField(blank=True, max_length=254)),
                ('passenger_phone', models.CharField(blank=True, max_length=20)),
                ('seats', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.busjourney')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('origin_lat', models.FloatField(default=0.0)),
                ('origin_lng', models.FloatField(default=0.0)),
                ('destination_lat', models.FloatField(default=0.0)),
                ('destination_lng', models.FloatField(default=0.0)),
                ('distance_km', models.FloatField(default=0.0)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('base_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buses', models.ManyToManyField(related_name='routes', to='booking.bus')),
            ],
            options={
                'ordering': ['origin', 'destination'],
            },
        ),
        migrations.AddField(
            model_name='busjourney',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='booking.route'),
        ),
    ]
